import type { NpcDefinition } from "@/lib/content/types";

export const allNpcs: NpcDefinition[] = [
  {
    id: "halloway",
    name: "Mr. Halloway",
    age: 34,
    gender: "male",
    profession: "Junior Ship's Architect",
    socialClass: "crew",
    personality: "Anxious, meticulous, quietly principled.",
    goals: "Wants the ship's design flaws taken seriously before it's too late.",
    fears: "Being blamed, or worse, ignored, if something goes wrong.",
    secrets:
      "Believes the watertight compartments do not extend high enough to survive a serious breach.",
    startingLocationId: "engine_room_access",
    schedule: [
      { afterMinutes: 0, locationId: "engine_room_access" },
      { afterMinutes: 180, locationId: "bridge_wing" },
    ],
    startingInventory: ["engineering_notes"],
    startingRelationship: { trust: 30, respect: 40, fear: 10, suspicion: 20, loyalty: 20 },
  },
  {
    id: "ashford",
    name: "Mrs. Ashford",
    age: 41,
    gender: "female",
    profession: "First-Class Passenger",
    socialClass: "first",
    personality: "Warm but easily flustered.",
    goals: "Find her husband, who went to dinner and never returned.",
    fears: "Losing her husband, being alone in an emergency.",
    secrets: "None of consequence — she is exactly as worried as she seems.",
    startingLocationId: "b_deck_corridor",
    schedule: [{ afterMinutes: 0, locationId: "b_deck_corridor" }],
    startingInventory: [],
    startingRelationship: { trust: 35, respect: 30, fear: 15, suspicion: 10, loyalty: 20 },
  },
  {
    id: "reilly",
    name: "Officer Reilly",
    age: 29,
    gender: "male",
    profession: "Deck Officer",
    socialClass: "crew",
    personality: "By-the-book, but not unkind.",
    goals: "Keep order and follow proper procedure.",
    fears: "A scandal, or a mistake that costs lives.",
    secrets: "None.",
    startingLocationId: "boat_deck",
    schedule: [{ afterMinutes: 0, locationId: "boat_deck" }],
    startingInventory: [],
    startingRelationship: { trust: 25, respect: 30, fear: 10, suspicion: 25, loyalty: 15 },
  },
  {
    id: "cobb",
    name: "Danny Cobb",
    age: 23,
    gender: "male",
    profession: "Third-Class Passenger",
    socialClass: "third",
    personality: "Streetwise, guarded, opportunistic but not cruel.",
    goals: "Make it to America with something worth having.",
    fears: "Being caught, being poor forever.",
    secrets: "Carries a lockpick set and knows a way past most locked doors.",
    startingLocationId: "g_deck_thirdclass_berths",
    schedule: [{ afterMinutes: 0, locationId: "g_deck_thirdclass_berths" }],
    startingInventory: ["lockpick_set"],
    startingRelationship: { trust: 20, respect: 15, fear: 5, suspicion: 40, loyalty: 10 },
  },
];

export const npcsById = Object.fromEntries(allNpcs.map((n) => [n.id, n]));
