
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Read DATABASE_URL directly (rather than the `env()` helper from
// "prisma/config", which throws if the variable is unset) so that
// `prisma generate` — which needs no live connection — still succeeds
// during the very first deploy, before a database has been provisioned.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
